//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> Id_product { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<double> sum { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> category { get; set; }
        public string forwhat { get; set; }
        public string uniquename { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
